services:
  - name: admin-api
    type: web
    env: java
    build_command: mvn clean package
    start_command: java -jar adminapi.jar
    dockerfile_path: ./admin-api/Dockerfile

  - name: bot-api
    type: web
    env: java
    build_command: mvn clean package
    start_command: java -jar botapi.jar
    dockerfile_path: ./bot-api/Dockerfile